---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    attributes:
      mysql:
        root_password: "root"
        socket: "/var/run/mysql-default/mysqld.sock"
  - name: centos-7.0
    attributes:
      mysql:
        root_password: "root"
        socket: "/var/run/mysql-default/mysqld.sock"
  - name: debian-7.4
    attributes:
      mysql:
        root_password: "root"
        socket: "/run/mysql-default/mysqld.sock"
  - name: ubuntu-10.04
    attributes:
      mysql:
        root_password: "root"
        socket: "/run/mysql-default/mysqld.sock"
  - name: ubuntu-12.04
    attributes:
      mysql:
        root_password: "root"
        socket: "/run/mysql-default/mysqld.sock"
  - name: ubuntu-14.04
    attributes:
      mysql:
        root_password: "root"
        socket: "/run/mysql-default/mysqld.sock"

suites:
  - name: employees51
    excludes:
      - centos-7.0
      - debian-7.4
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[mysql-test-schema::employees]
    attributes:
      mysql:
        version: "5.1"

  - name: employees55
    excludes:
      - ubuntu-10.04
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[mysql-test-schema::employees]
    attributes:
      mysql:
        version: "5.5"

  - name: employees56
    excludes:
      - debian-7.4
      - ubuntu-10.04
      - ubuntu-12.04
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[mysql-test-schema::employees]
    attributes:
      mysql:
        version: "5.6"

  - name: sakila51
    excludes:
      - centos-7.0
      - debian-7.4
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[mysql-test-schema::sakila]
    attributes:
      mysql:
        version: "5.1"

  - name: sakila55
    excludes:
      - ubuntu-10.04
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[mysql-test-schema::sakila]
    attributes:
      mysql:
        version: "5.5"

  - name: sakila56
    excludes:
      - debian-7.4
      - ubuntu-10.04
      - ubuntu-12.04
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[mysql-test-schema::sakila]
    attributes:
      mysql:
        version: "5.6"
